{
  "formatVersion": "1.1",
  "component": {
    "group": "com.irdb",
    "module": "irkit-analytics",
    "version": "2026.3.080320261245",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.3.080320261245.aar",
          "url": "irkit-analytics-2026.3.080320261245.aar",
          "size": 332022,
          "sha512": "46997cee8fa528dad6cc527166b543375a1cb32ebe4479b931c6c2484855151e5ac466be25969549fe56bcbac48455aaaeb84c08d82867251d5b852ad8815c7a",
          "sha256": "a9af2f6fe7388f44dcf4cdde48bfce088398529d0ed8fb5f54bd796c31dd850b",
          "sha1": "3b0db79d09f6488c244adfcd6d55436042098105",
          "md5": "d860e2e09f11575e5efc0b6bd88b7bd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.irdb",
          "module": "irkit-logging",
          "version": {
            "requires": "2026.3.080320261245"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "irkit-analytics-2026.3.080320261245.aar",
          "url": "irkit-analytics-2026.3.080320261245.aar",
          "size": 332022,
          "sha512": "46997cee8fa528dad6cc527166b543375a1cb32ebe4479b931c6c2484855151e5ac466be25969549fe56bcbac48455aaaeb84c08d82867251d5b852ad8815c7a",
          "sha256": "a9af2f6fe7388f44dcf4cdde48bfce088398529d0ed8fb5f54bd796c31dd850b",
          "sha1": "3b0db79d09f6488c244adfcd6d55436042098105",
          "md5": "d860e2e09f11575e5efc0b6bd88b7bd7"
        }
      ]
    }
  ]
}
